### PR TITLE
Add methods

### PR DESCRIPTION
**Pull request by xiCO2k**
- Add onTouch and onTouchEnd props
- Add reset method

### CODE REVIEW

**Comment by xiCO2k** [comment]
Awesome Thanks ;)

**Comment by xiCO2k** [comment]
Hey @edanedison just checked the npm and looks like the lib/index.js does not have the changes.

**Comment by xiCO2k** [comment]
thanks for bumping the 1.0.12 ;)

**Comment by edanedison** [comment]
body{font-family:Helvetica,Arial;font-size:13px}No problem :)  Edan On 21 February 2020 at 16:53:53, Francisco Madeira (notifications@github.com) wrote: 





thanks for bumping the 1.0.12 ;)
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Pull request merged**
